// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/fardinabir/go-svc-boilerplate/internal/cases"
	"github.com/fardinabir/go-svc-boilerplate/internal/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHandlers is the Wire injector: it declares WHAT each domain needs and
// lets Wire generate the wiring into wire_gen.go. The body is replaced entirely by
// generated code — do not edit. Run `make wire` after changing a provider set.
func InitializeHandlers(db *gorm.DB) (*Handlers, error) {
	repository := user.NewRepository(db)
	service := user.NewService(repository)
	handler := user.NewHandler(service)
	casesRepository := cases.NewRepository(db)
	casesService := cases.NewService(casesRepository, service)
	casesHandler := cases.NewHandler(casesService)
	handlers := &Handlers{
		User:  handler,
		Cases: casesHandler,
	}
	return handlers, nil
}
